#pragma once
#define ICON_SHADOWMAP_ON		8
#define ICON_SHADOWMAP_OFF		9

#define ICON_COLORMAP_ON		10
#define ICON_COLORMAP_OFF		11
#define ICON_TILECOLOR_ON		12
#define ICON_TILECOLOR_OFF		13
#define ICON_LIGHTING_ON		14
#define ICON_LIGHTING_OFF		15
#define ICON_TEXTURE_ON			16
#define ICON_TEXTURE_OFF		17
#define ICON_SMOOTH_COLOR_ON	18
#define ICON_SMOOTH_COLOR_OFF	19
#define ICON_EMPTYTILE_ON		20
#define ICON_EMPTYTILE_OFF		21
#define ICON_ALL_LIGHTS_ON		22
#define ICON_ALL_LIGHTS_OFF		23
#define ICON_LIGHTSPHERE_ON		24
#define ICON_LIGHTSPHERE_OFF	25

#define ICON_GRID_SNAP_ON		32
#define ICON_GRID_SNAP_OFF		33
#define ICON_VIEWOPTIONS		34


#define ICON_UNDO				36
#define ICON_REDO				37
#define ICON_COPY				38
#define ICON_PASTE				39

#define ICON_MOVE				40
#define ICON_ROTATE				41
#define ICON_SCALE				42

#define ICON_ORTHO				44
#define ICON_PERSPECTIVE		45

#define ICON_PIVOT_ROT_LOCAL	48
#define ICON_PIVOT_ROT_GLOBAL	49

#define ICON_OBJECTPICKER_OPEN	52
#define ICON_OBJECTPICKER_CLOSE	53

#define ICON_NOICON				63
