#pragma once
#define ICON_EDIT_HEIGHT		0
#define ICON_EDIT_TEXTURE		1
#define ICON_EDIT_OBJECT		2
#define ICON_EDIT_WALL			3
#define ICON_EDIT_GAT			4


#define ICON_SHADOWMAP_ON		10
#define ICON_SHADOWMAP_OFF		11
#define ICON_COLORMAP_ON		12
#define ICON_COLORMAP_OFF		13
#define ICON_TILECOLOR_ON		14
#define ICON_TILECOLOR_OFF		15
#define ICON_LIGHTING_ON		16
#define ICON_LIGHTING_OFF		17
#define ICON_TEXTURE_ON			18
#define ICON_TEXTURE_OFF		19
#define ICON_SMOOTH_COLOR_ON	20
#define ICON_SMOOTH_COLOR_OFF	21
#define ICON_EMPTYTILE_ON		22
#define ICON_EMPTYTILE_OFF		23
#define ICON_ALL_LIGHTS_ON		24
#define ICON_ALL_LIGHTS_OFF		25
#define ICON_LIGHTSPHERE_ON		26
#define ICON_LIGHTSPHERE_OFF	27

#define ICON_VIEW_MODEL_ON		30
#define ICON_VIEW_MODEL_OFF		31
#define ICON_VIEW_EFFECT_ON		32
#define ICON_VIEW_EFFECT_OFF	33
#define ICON_VIEW_LIGHT_ON		34
#define ICON_VIEW_LIGHT_OFF		35
#define ICON_VIEW_SOUND_ON		36
#define ICON_VIEW_SOUND_OFF		37
#define ICON_VIEW_WATER_ON		38
#define ICON_VIEW_WATER_OFF		39

#define ICON_GRID_SNAP_ON		40
#define ICON_GRID_SNAP_OFF		41
#define ICON_VIEWOPTIONS		42


#define ICON_UNDO				45
#define ICON_REDO				46
#define ICON_COPY				47
#define ICON_PASTE				48

#define ICON_MOVE				50
#define ICON_ROTATE				51
#define ICON_SCALE				52
#define ICON_ROTATE_RIGHT		53

#define ICON_ORTHO				55
#define ICON_PERSPECTIVE		56
#define ICON_MIRROR_HORIZONTAL	57
#define ICON_MIRROR_VERTICAL	58

#define ICON_PIVOT_ROT_LOCAL	60
#define ICON_PIVOT_ROT_GLOBAL	61
#define ICON_HEIGHT_SPLIT_1		62
#define ICON_HEIGHT_SPLIT_2		63

#define ICON_OBJECTPICKER_OPEN	65
#define ICON_OBJECTPICKER_CLOSE	66
#define ICON_TEXTUREPICKER_OPEN	67
#define ICON_TEXTUREPICKER_CLOSE	68

#define ICON_TEXTUREBRUSH_STAMP	70
#define ICON_TEXTUREBRUSH_BUCKET	71
#define ICON_TEXTUREBRUSH_SELECT	72

#define ICON_SELECT_RECTANGLE	75
#define ICON_SELECT_LASSO		76
#define ICON_SELECT_WAND_TEX	77
#define ICON_SELECT_WAND_HEIGHT	78
#define ICON_SELECT_ALL_TEX		79
#define ICON_SELECT_ALL_HEIGHT	74

#define ICON_HEIGHT_SELECT_CENTER	80
#define ICON_HEIGHT_SELECT_CORNERS	81
#define ICON_HEIGHT_SELECT_SIDES	82
#define ICON_HEIGHT_DOODLE			83

#define ICON_WALL_ADD_REMOVE		85

#define ICON_NOICON				99
